apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikubegraph
  namespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: graphql-namespace
    
  project: default
  source:
    repoURL: https://github.com/amadouth6/argocd.git
    targetRevision: minikube-cluster
    path: swh-graphql/
    helm:
      releaseName: minikubegraph
      valueFiles:
        - myvalues.yaml

  syncPolicy:
    syncOptions:
      - CreateNamespace=true    
    
    automated:
      selfHeal: true
      prune: true
